export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILED = "FETCH_EMPLOYEE_FAILED";

export const CREATE_EMPLOYEE_CREATE_SALARY_REQUEST = "CREATE_EMPLOYEE_CREATE_SALARY_REQUEST";
export const CREATE_EMPLOYEE_CREATE_SALARY_SUCCESS = "CREATE_EMPLOYEE_CREATE_SALARY_SUCCESS";
export const CREATE_EMPLOYEE_CREATE_SALARY_FAILED = "CREATE_EMPLOYEE_CREATE_SALARY_FAILED";

export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_REQUEST = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_REQUEST";
export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_SUCCESS = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_SUCCESS";
export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_FAILED = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_FAILED";
