export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILED = "FETCH_EMPLOYEE_FAILED";

export const   ADD_EMPLOYEE_COMMISSION_REQUEST = "ADD_EMPLOYEE_COMMISSION_REQUEST";
export const ADD_EMPLOYEE_COMMISSION_SUCCESS = "ADD_EMPLOYEE_COMMISSION_SUCCESS";
export const ADD_EMPLOYEE_COMMISSION_FAILED = "ADD_EMPLOYEE_COMMISSION_FAILED ";

export const  ADD_EMPLOYEE_lOAN_REQUEST = "ADD_EMPLOYEE_lOAN_REQUEST";
export const ADD_EMPLOYEE_lOAN_SUCCESS = "ADD_EMPLOYEE_lOAN_SUCCESS";
export const ADD_EMPLOYEE_lOAN_FAILED = "ADD_EMPLOYEE_lOAN_FAILED ";

export const  ADD_EMPLOYEE_SATURATION_DEDUCTION_REQUEST = "ADD_EMPLOYEE_SATURATION_DEDUCTION_REQUEST";
export const ADD_EMPLOYEE_SATURATION_DEDUCTION_SUCCESS = "ADD_EMPLOYEE_SATURATION_DEDUCTION_SUCCESS";
export const ADD_EMPLOYEE_SATURATION_DEDUCTION_FAILED = "ADD_EMPLOYEE_SATURATION_DEDUCTION_FAILED ";

export const  ADD_EMPLOYEE_OTHER_REQUEST = "ADD_EMPLOYEE_OTHER_REQUEST";
export const ADD_EMPLOYEE_OTHER_SUCCESS = "ADD_EMPLOYEE_OTHER_SUCCESS";
export const ADD_EMPLOYEE_OTHER_FAILED = "ADD_EMPLOYEE_OTHER_FAILED ";

export const  ADD_EMPLOYEE_OVERTIME_REQUEST = "ADD_EMPLOYEE_OVERTIME_REQUEST";
export const ADD_EMPLOYEE_OVERTIME_SUCCESS = "ADD_EMPLOYEE_OVERTIME_SUCCESS";
export const ADD_EMPLOYEE_OVERTIME_FAILED  = "ADD_EMPLOYEE_OVERTIME_FAILED ";



export const CREATE_EMPLOYEE_CREATE_SALARY_REQUEST = "CREATE_EMPLOYEE_CREATE_SALARY_REQUEST";
export const CREATE_EMPLOYEE_CREATE_SALARY_SUCCESS = "CREATE_EMPLOYEE_CREATE_SALARY_SUCCESS";
export const CREATE_EMPLOYEE_CREATE_SALARY_FAILED = "CREATE_EMPLOYEE_CREATE_SALARY_FAILED";

export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_REQUEST = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_REQUEST";
export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_SUCCESS = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_SUCCESS";
export const CREATE_EMPLOYEE_CREATE_ALLOWANCE_FAILED = "CREATE_EMPLOYEE_CREATE_ALLOWANCE_FAILED";
